### PR TITLE
changed font to md:2xl

### PR DESCRIPTION
**Pull request by tarunsamanta2k20**
changed both the headers fonts to md:2xl.

### CODE REVIEW

**Review by brandonbyr4 — CHANGES_REQUESTED** [review]
Can you keep the text-3xl class, but just add the new one?   So both are on there.

**Comment by tarunsamanta2k20** [comment]
okay making changes

**Comment by tarunsamanta2k20** [comment]
Please check and let me know if any changes required

**Comment by brandonbyr4** [comment]
@tarunsamanta2k20 looks perfect, thanks for the contribution! 🎉

**Pull request merged**
